DELETE FROM AVION;
DELETE FROM EMPLOYEE;
DELETE FROM ESCALE;
DELETE FROM MISSION;
DELETE FROM VILLE;

/* remis la sequence à 0.
ALTER SEQUENCE INCREASE_SEQ INCREMENT BY -531;
SELECT INCREASE_SEQ.NEXTVAL  FROM dual;
 --xym
ALTER SEQUENCE INCREASE_SEQ increment by 1;
SELECT INCREASE_SEQ.NEXTVAL FROM dual;
*/



